'use client';
import { useState } from 'react';
/* eslint-disable @next/next/no-img-element -- small static brand image in a marketing illustration */
import { CheckCircle2, Circle, CircleDashed, Plus, Search, ChevronDown, LayoutGrid, List, Home, Folder, FileText, Activity, Users, ArrowUpRight } from 'lucide-react';
import { initialTasks, statusLabels, type Status } from '@/lib/demo';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import Link from 'next/link';
export function Avatar({name,small=false}:{name:string;small?:boolean}){return <span title={name} className={`avatar ${small?'small':''} person-${name.split(' ')[0].toLowerCase()}`}>{name.split(' ').map(x=>x[0]).join('')}</span>}
export function StatusIcon({status}:{status:Status}) {const Icon=status==='DONE'?CheckCircle2:status==='IN_PROGRESS'?CircleDashed:Circle;return <Icon size={16} className={`status-${status}`}/>}
export function ProductPreview(){const [view,setView]=useState('list');return <div className="product-window"><div className="preview-top"><span className="mini-brand"><img src="/brand/plane.png" alt=""/>Studio workspace <ChevronDown size={13}/></span><span className="preview-search"><Search size={13}/>Search your workspace <kbd>⌘ K</kbd></span><Avatar name="Yash Lalwani" small/></div><div className="preview-body"><aside className="preview-sidebar"><span className="preview-side-title">Workspace</span><span><Home/>Overview</span><span><Folder/>Projects</span><span><FileText/>Notes</span><span><Activity/>Activity</span><span className="preview-side-title">Your projects</span><span className="selected"><span className="project-mark">W</span>Website relaunch</span><span><span className="project-mark lilac">M</span>Mobile app beta</span><span><Users/>Members</span><div className="preview-sidebar-bottom">A place for your next big idea.</div></aside><div className="preview-main"><div className="preview-project"><strong><span className="project-mark">W</span>Website relaunch</strong><div className="avatar-stack">{['Alex Morgan','Priya Shah','Sam Wilson'].map(n=><Avatar key={n} name={n} small/>)}</div></div><div className="preview-toolbar"><span>Tasks <b>9</b></span><Tabs value={view} onValueChange={setView}><TabsList><TabsTrigger value="list"><List size={13}/>List</TabsTrigger><TabsTrigger value="board"><LayoutGrid size={13}/>Board</TabsTrigger></TabsList></Tabs><Link href="/projects" className="preview-add"><Plus size={12}/>Add task</Link></div>{view==='list'?<div className="preview-task-list">{(['IN_PROGRESS','TODO','DONE'] as Status[]).map(status=><div key={status}><div className="preview-group"><StatusIcon status={status}/>{statusLabels[status]}<small>3</small></div>{initialTasks.filter(t=>t.status===status).map(t=><Link href="/projects" className="preview-row" key={t.id}><span className="task-code">{t.id}</span><span className="preview-task-title">{t.title}</span><Avatar name={t.person} small/><span className={`priority priority-${t.priority}`}>{t.priority.toLowerCase()}</span><span className="preview-date">{t.due}</span></Link>)}</div>)}</div>:<div className="preview-board">{(['TODO','IN_PROGRESS','DONE'] as Status[]).map(status=><div key={status}><div className="preview-group"><StatusIcon status={status}/>{statusLabels[status]}</div>{initialTasks.filter(t=>t.status===status).map(t=><Link href="/projects" className="preview-card" key={t.id}><span className="task-code">{t.id}</span><p>{t.title}</p><div><span className={`priority priority-${t.priority}`}>{t.priority.toLowerCase()}</span><Avatar name={t.person} small/></div></Link>)}</div>)}</div>}<div className="preview-bottom"><span>Everything in its place.</span><Link href="/about#try-plane">Try the demo account <ArrowUpRight size={13}/></Link></div></div></div></div>}
